### ISSUE TITLE
older version of jose has issue with x5c in jwks key

### ISSUE THREAD

**Issue by tommyk** [auth0/node-jwks-rsa#279] opened 2021-11-10 19:23 UTC
### Describe the problem

we are trying to use this library to validate a JWS object with JWKS keystore.  the keystore endpoint comes back with valid JWKS keys, but when the object is trying to be verified, we get an error.  i've tracked it down to a jose error like below.

```
JWKInvalid: `x5c` member at index 0 is not a valid base64-encoded DER PKIX certificate
```

using jose version 4.2.1 directly, we can load the jwks and verify the object correctly.  using jose version 2.0.5 (which this library uses), gives this error above as well.

it seems that this jose version is quite old and has bugs/features missing from the 4.x.x releases.  it would be nice to move to that version, as it would keep the library updated, and also fixes this issue.  i haven't tried to upgrade, but i am guessing there are quite a few code changes that will have to take place.

thoughts?

### What was the expected behavior?

to verify the jws object without throwing an error.

### Reproduction

i don't have a sample codebase to illustrate this problem, but i am sure i can whip something up if required.  testing directly against jose to see that the behavior works in latest version is much easier.

### Environment

- **Version of this library used:2.0.5**
- **Which framework are you using, if applicable: nodejs**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by panva** [comment] 2021-11-15 07:34
This is not a bug in `jose`, it is in fact validating the `x5c` member. The `jwks_uri` may simply be using `x5c` wrong, care to share the content of your JSON Web Key Set?

**Comment by tommyk** [comment] 2021-11-15 17:26
it works correctly in the latest jose version, but not in the 2.0.5 version.  so i would say that the jwks set is correct, its just doesn't work correctly with the older version.  maybe i am wrong on that, i can try and work on giving an example if that helps. 

but just so you know, we have it up and running using the latest jose version ourselves, hoping that we can get this library updated so we can have things like caching and not basically rebuilding this library ourselves.

**Comment by panva** [comment] 2021-11-15 17:29
@tommyk can you show the JSON Web Key Set content? I'm fairly certain it's just invalid in some way.

**Comment by panva** [comment] 2021-11-15 17:32
> edit: sorry, i re-read your message and now see what you are saying that the newer 4.x version does NOT validate x5c where as the 2.x does. why would they have taken that away?

I've not carried that check along because it's fairly resource consuming to be checking that the x5c[0] contents match the other JWK members. Given that the x5c is not used by the library at all it's not necessary to perform said check.

**Comment by adamjmcgrath** [comment] 2022-01-27 13:59
Closing - thanks @panva

**Closed by adamjmcgrath** 2022-01-27 13:59 UTC
