### ISSUE TITLE
Error: Cannot find module 'jsonwebtoken'

### ISSUE THREAD

**Issue by andkh** [auth0/node-jwks-rsa#90] opened 2019-05-13 09:45 UTC
Hello everyone,

As I understand with the last update  on May 9, 2019 lib integrated with 'passport-jwt' which use 'jsonwebtoken' inside. 
So, for now, 'jsonwebtoken' exist only in devDependencies package.json and it will be a problem because lib using it not only for dev.
https://github.com/auth0/node-jwks-rsa/commit/8760bb26d63c80e5aea088f1d0d1585bebca364d#diff-df829a25c0749c2341fe4d27680067a9

For now, I need to install 'jsonwebtoken' manually.

Thanks,
Andrew

**Comment by simov** [comment] 2019-05-13 21:51
https://github.com/auth0/node-jwks-rsa/pull/89

**Comment by lbalmaceda** [comment] 2019-05-14 17:10
@simov I think the idea of using an integration is that you already have that platform (passport in this case) as a dependency of your app. If you see, passport today is also a devDependency, and you're only pointing out that the issue is on the jsonwebtoken one. 
If your app is going to be using passport, your app is probably defining it as dependency (vs devDependency). The same should be with jsonwebtoken. I think the fix here is not to move it to the dependencies block, as this library doesn't make use of it at all.. only the passport integration does, and that's optional.

Fix is probably relying on documenting the use of the integration, and saying that if you're going to use it on a passport enabled app you'll need to add as well the jsonwebtoken dependency in the dependencies block.

**Comment by simov** [comment] 2019-05-14 17:23
The problem with your [index.js](https://github.com/auth0/node-jwks-rsa/blob/master/src/index.js) file is that you are require'ing everything during initialization. Meaning that all require's have to be resolved, no matter what I use, or I do not use in my app.

If you really want to make the passport integration optional, then instead of require'ing it during initialization, let the user call a function to require it.

Essentially you are releasing a minor version that breaks all apps/builds, and the solution is to include another module in my app, that I don't even use?

**Comment by lbalmaceda** [comment] 2019-05-14 21:58
IMO the passport integration should be optional. Not everyone will like adding `jsonwebtoken` as a dependency of their app just to skip this "require error" if they are not going use it at all. Then the fix can be checking if the passport module is present and only then require that integration file, which will of course require the jwt library as well. That's something we can document.

**Comment by sirgalleto** [comment] 2019-05-14 23:03
@lbalmaceda Thank you for your response. 

I'm wondering right now about having a stable package. What we spect as users of the library is to install it and use it with any problem. In this case, as @simov mentioned, this package is breaking the apps/builds due to the missing package. 

So, even though you want to add this to the documentation, in order to offer a good developer experience (and avoid breaking many applications), I'd prefer (and I really) to resolve all the needed dependencies under the installation. 

We know that the passport integration should be optional; in this case, some solutions can be taken into account; for now, I can think of:  

1. Add the `jsonwebtoken` as [peerDependency](https://nodejs.org/es/blog/npm/peer-dependencies/)
2. Use lazy initialization for the passport module. 
3. Create a custom package for that integration. So we would not add unused code into our build.

But the most crucial part today is to release a usable version of the package and avoid breaking more applications. There is already a PR with a quick fix #89, which is even faster than adding a section into the documentation. Does this sound reasonable?

**Comment by damieng** [comment] 2019-05-14 23:30
The "quick fix" in #89 may solve it for you but bring issues for other people.

The quick workaround for anyone is to pin the node-jwks-rsa dependency at 1.4.0 - there are no other changes in 1.5.0 other than enabling passport integration.

**Comment by damieng** [comment] 2019-05-21 15:50
So we've looked at the options and there isn't a good way of making these dependencies optional without introducing a breaking change.  So the plan is:

We publish a 1.5.1 with the missing dependency to get people unblocked - especially if they specifying minor or patch compatibility with 1.x.y

We publish a 2.x that has a breaking change allowing these packages to be peers instead.

**Comment by damieng** [comment] 2019-05-21 17:19
Merged in, going out in 1.5.1

**Closed by damieng** 2019-05-21 17:19 UTC

**Comment by damieng** [comment] 2019-05-22 00:12
1.5.1 is now out and includes this and various dependency updates.

**Comment by sirgalleto** [comment] 2019-05-23 18:24
Great!! TY for keep us updated.

**Comment by mustafayildiz-m** [comment] 2020-10-14 17:33
ı cant find the problem which jsonwebtoken file cannot find by node
