### ISSUE TITLE
koa example doesn't pass TS typechecker

### ISSUE THREAD

**Issue by samuela** [auth0/node-jwks-rsa#75] opened 2019-01-25 08:49 UTC
I just tried the koa example (or at least an instantiation of almost exactly the same thing in my proiject), and I'm getting a TypeScript:
```
/nu/.links/skainswo/api/node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/server.ts(15,5): error TS2322: Type '(name: string, scheme: string, options?: any) => void' is not assignable to type 'string | string[] | Buffer | Buffer[] | SecretLoader'.
  Type '(name: string, scheme: string, options?: any) => void' is not assignable to type 'SecretLoader'.
    Type 'void' is not assignable to type 'Promise<string | string[] | Buffer | Buffer[]>'.
src/server.ts(25,3): error TS2554: Expected 2-4 arguments, but got 1.

    at createTSError (/nu/.links/skainswo/api/node_modules/ts-node/src/index.ts:261:12)
    at getOutput (/nu/.links/skainswo/api/node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (/nu/.links/skainswo/api/node_modules/ts-node/src/index.ts:558:11)
    at Module.m._compile (/nu/.links/skainswo/api/node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/nu/.links/skainswo/api/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
```
I have "jwks-rsa": "^1.3.0", "koa-jwt": "^3.5.1".

**Comment by crivera** [comment] 2019-02-25 15:57
i see the same issue... did you find a fix for it?

**Comment by samuela** [comment] 2019-02-25 19:52
@crivera I'm not sure that a workaround is possible without fixing the type signatures. It looks like #80 should fix it, but that PR has been open for 3 weeks now. I'm beginning to think this repo isn't actively maintained.

**Comment by samuela** [comment] 2019-10-27 19:34
bump

**Comment by samuela** [comment] 2020-01-26 00:13
Bump

**Comment by samuela** [comment] 2020-04-25 02:40
Bump

**Comment by samuela** [comment] 2020-07-24 03:50
Bump

**Comment by davidpatrick** [comment] 2020-09-21 23:50
Looks like this issue may have been resolved in https://github.com/auth0/node-jwks-rsa/pull/80 referenced in https://github.com/auth0/node-jwks-rsa/issues/46

I am running the example with `ts-node server.js` without any problems.  Can you help me reproduce this issue, considering it still is one?

**Comment by davidpatrick** [comment] 2020-09-22 18:26
Related https://github.com/auth0/node-jwks-rsa/issues/78

**Closed by davidpatrick** 2020-09-22 18:26 UTC
Labels: bug
